spring:
   profiles:
     datasource:
       driverClassName: com.mysql.jdbc.Driver
       url: jdbc:mysql://127.0.0.1:3306/aaa?useUnicode=true&characterEncoding=GBK
       username: root
       password: 123456
       initialSize: 1
       maxActive: 15
       maxIdle: 16
       maxWait: 30000
       minEvictableIdleTimeMillis: 300000
       minIdle: 10
       numTestsPerEvictionRun: 3
       testOnBorrow: false
       validationQuery: select 'x'
       testWhileIdle: true
       timeBetweenEvictionRunsMillis: 10000

     mybatis:
       mapperLocation: classpath:/*.xml
       typeAliasesPackage: com.heidou.model.BookDo
